### PR TITLE
WIP: Update Website Content

### PR DESCRIPTION
**Pull request by sebastianrosenzweig**
Let's track all incoming content updates in this branch... not yet ready to merge...

### CODE REVIEW

**Comment by bytesnake** [comment]
are you trying to trigger CI? It's currently restricted to push-only [here](https://github.com/aes-erlangen/aes-erlangen.github.io/blob/main/.github/workflows/deploy.yml#L2)

**Comment by sebastianrosenzweig** [comment]
> are you trying to trigger CI? It's currently restricted to push-only [here](https://github.com/aes-erlangen/aes-erlangen.github.io/blob/main/.github/workflows/deploy.yml#L2)

Yes!! :-D What does it mean, how do I have to modify to see changes?

**Comment by sebastianrosenzweig** [comment]
For some reason I always get an error:  ```Set the GITHUB_TOKEN or TOKEN env variables.```
See [here](https://github.com/sebastianrosenzweig/aes-erlangen.github.io/runs/5993642700?check_suite_focus=true)

**Comment by bytesnake** [comment]
yeah because your fork does not have the same environment variables, if you try to copy it will probably pushed into the main's gh-pages branch

**Comment by bytesnake** [comment]
but you can install [zola](https://www.getzola.org/documentation/getting-started/installation/) and just run `zola serve` which will also automatically refresh the page when something changes

**Comment by sebastianrosenzweig** [comment]
> but you can install [zola](https://www.getzola.org/documentation/getting-started/installation/) and just run `zola serve` which will also automatically refresh the page when something changes

Thanks for the hint! I will add this to the README...

**Pull request merged**
